apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rdllm-audit
  labels:
    app.kubernetes.io/name: rdllm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
