apiVersion: v1
kind: Service
metadata:
  name: rdllm-service
  labels:
    app.kubernetes.io/name: rdllm
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rdllm
    app.kubernetes.io/component: service
  ports:
    - name: http
      port: 8765
      targetPort: http
